# Generated by Django 3.0.6 on 2020-06-27 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_information',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='用户名')),
                ('password', models.CharField(max_length=20, verbose_name='密码')),
                ('level', models.CharField(max_length=10, verbose_name='权限等级')),
            ],
        ),
    ]
